#!/bin/bash
set -euo pipefail
image=thavlik/foldy
tag=latest
docker build -t $image:$tag .
docker run \
    -v C:/Users/tlhavlik/.aws:/root/.aws \
    -it \
    --name foldy \
    --rm \
    $image:$tag \
    python3 ./simulate.py \
        --pdb_id 1aki \
        --model_id 0 \
        --chain_id A \
        --correlation_id 0 \
        --nsteps 10
