#!/bin/bash
set -euo pipefail
image=thavlik/foldy
tag=latest
docker build -t $image:$tag .

pdb_id=4a5u
model_id=1
chain_id=A
primary=MHHHHHHGSSQLLPAPLTNDPTAIGPVLPFEELHPRRYPENTATFLTRLRSLPSNHLPQPTLNCLLSAVSDQTKVSEEHLWESLQTILPDSQLSNEETNTLGLSTEHLTALAHLYNFQATVYSDRGPILFGPSDTIKRIDITHTTGPPSHFSPGKRLLGS
mask=------------++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

#--pdb_id 4jrn \
#--model_id 1 \
#--chain_id A \
#--primary GAHMSELVFEKADSGCVIGKRILAHMQEQIGQPQALENSERLDRILTVAAWPPDVPKRFVSVTTGETRTLVRGAPLGSGGFATVYEATDVETNEELAVKVFMSEKEPTDETMLDLQRESSCYRNFSLAKTAKDAQESCRFMVPSDVVMLEGQPASTEVVIGLTTRWVPNYFLLMMRAEADMSKVISWVFGDASVNKSEFGLVVRMYLSSQAIKLVANVQAQGIVHTDIKPANFLLLKDGRLFLGDFGTYRINNSVGRAIGTPGYEPPERPFQATGITYTFPTDAWQLGITLYCIWCKERPTPADGIWDYLHFADCPSTPELVQDLIRSLLNRDPQKRMLPLQALETAAFKEMDSVVKGAAQNFEQQEHLHTE \
#--mask '----++++++++++++++++++++++++-------++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--+++++++++++----++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------' \
#    -v C:/Users/tlhavlik/Repositories/foldy/pdb:/data \

docker run \
    -v C:/Users/tlhavlik/.aws:/root/.aws \
    -v D:/casp11:/data \
    -e PROTEINNET_PATH=/data \
    -it \
    --name foldy \
    --rm \
    $image:$tag \
    python3 normalize.py

    #./fake-sim.sh /data/1aki.pdb


    #-v D:/casp11:/data \
    #python3 ./simulate.py \
    #    --no_report \
    #    --correlation_id 0 \
    #    --pdb_id $pdb_id \
    #    --model_id $model_id \
    #    --chain_id $chain_id \
    #    --primary $primary \
    #    --mask $mask \
    #    --nsteps 10
        