kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: foldy-big-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: "do-block-storage"
  