apiVersion: v1
kind: Service
metadata:
  name: foldy-operator
spec:
  selector:
    app: foldy-operator
  ports:
  - port: 8090
    targetPort: 8090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foldy-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: foldy-operator-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: foldy-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: foldy-operator-role
subjects:
- kind: ServiceAccount
  name: foldy-operator
---
apiVersion: v1
kind: Service
metadata:
  name: foldy-operator-redis
spec:
  selector:
    app: foldy-operator-redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foldy-operator-redis
spec:
  selector:
    matchLabels:
      app: foldy-operator-redis
  template:
    metadata:
      labels:
        app: foldy-operator-redis
    spec:
      containers:
      - name: foldy-operator-redis
        image: redis:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foldy-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foldy-operator
  template:
    metadata:
      labels:
        app: foldy-operator
    spec:
      serviceAccountName: foldy-operator
      containers:
      - name: foldy-operator
        image: thavlik/foldy-operator:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "2048Mi"
            cpu: "500m"
        env:
          - name: REDIS_URI
            value: foldy-operator-redis:6379
          - name: GOGC # https://golang.org/pkg/runtime/
            value: '50'
        ports:
        - containerPort: 8090

